#define USART3_OSC_FREQUENCY 16000000UL // 16MHz
#define USART3_BAUD_RATE 9600 // bps

// Apply the UBRR formulae according to the Atmega 328 datasheet.
#define USART3_BRR_VALUE (unsigned long) round(USART3_OSC_FREQUENCY/16.0/USART3_BAUD_RATE) - 1

#define USART3_RX_ENABLE 1
#define USART3_TX_ENABLE 1

// #define USART3_RX_INT_ENABLE 1
// #define USART3_TX_INT_ENABLE 1
// #define USART3_UDR_INT_ENABLE 1

// #define USART3_CHARACTER_SIZE_5 1
// #define USART3_CHARACTER_SIZE_6 1
// #define USART3_CHARACTER_SIZE_7 1
#define USART3_CHARACTER_SIZE_8 1
// #define USART3_CHARACTER_SIZE_9 1

#define USART3_ASYNC_MODE 1
// #define USART3_SYNC_MODE 1
// #define USART3_MASTER_SPI_MODE 1

#define USART3_PARITY_CHECK_DISABLE 1
// #define USART3_PARITY_CHECK_ODD 1
// #define USART3_PARITY_CHECK_EVEN 1

#define USART3_STOP_BIT_ONE 1
// #define USART3_STOP_BIT_TWO 1

#define USART3_POLARITY_TX_RISING 1
// #define USART3_POLARITY_TX_FALLING 1
