#define USART2_OSC_FREQUENCY 16000000UL // 16MHz
#define USART2_BAUD_RATE_2 9600 // bps

// Apply the UBRR formulae according to the Atmega 328 datasheet.
#define USART2_BRR_VALUE (unsigned long) round(USART2_OSC_FREQUENCY/16.0/USART2_BAUD_RATE) - 1

#define USART2_RX_ENABLE 1
#define USART2_TX_ENABLE 1

// #define USART2_RX_INT_ENABLE 1
// #define USART2_TX_INT_ENABLE 1
// #define USART2_UDR_INT_ENABLE 1

// #define USART2_CHARACTER_SIZE_5 1
// #define USART2_CHARACTER_SIZE_6 1
// #define USART2_CHARACTER_SIZE_7 1
#define USART2_CHARACTER_SIZE_8 1
// #define USART2_CHARACTER_SIZE_9 1

#define USART2_ASYNC_MODE 1
// #define USART2_SYNC_MODE 1
// #define USART2_MASTER_SPI_MODE 1

#define USART2_PARITY_CHECK_DISABLE 1
// #define USART2_PARITY_CHECK_ODD 1
// #define USART2_PARITY_CHECK_EVEN 1

#define USART2_STOP_BIT_ONE 1
// #define USART2_STOP_BIT_TWO 1

#define USART2_POLARITY_TX_RISING 1
// #define USART2_POLARITY_TX_FALLING 1
